import { Ebook, SiteConfig, LocaleInfo, Translations, Language } from './types';

export const INITIAL_EBOOKS: Ebook[] = [
  {
    "id": "1",
    "title": "L'Éveil du Troisième Œil",
    "description": "Un guide complet pour explorer vos facultés intuitives et transcender la vision ordinaire.",
    "summary": "Ce livre vous enseigne les techniques ancestrales de méditation et de visualisation pour activer la glande pinéale. Apprenez à percevoir les énergies subtiles et à renforcer votre connexion avec l'univers.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=600&h=800",
    "officialPrice": 49.99,
    "promoPrice": 29.99,
    "chariowLink": "https://chariow.com/p/eveil-3-oeil",
    "isFeatured": true,
    "isPromo": true,
    "category": "Méditation",
    "customFields": [
      {
        "label": "Auteur",
        "value": "Maître Élysée"
      },
      {
        "label": "Pages",
        "value": "180"
      }
    ]
  },
  {
    "id": "2",
    "title": "✨ ÉVEIL ASTRAL",
    "description": "Brisez les blocages astraux, manifestez la Lumière Divine et réclamez enfin votre héritage céleste en seulement 21 jours.",
    "summary": "✨ Présentation\n\"ÉVEIL ASTRAL\" n'est pas qu'un simple livre, c'est un programme d'immersion de 21 jours conçu pour démanteler les forteresses spirituelles qui entravent votre épanouissement.\nCe que vous allez découvrir à l'intérieur :\n1.\tLe Diagnostic Spirituel : Apprenez à identifier précisément les \"portes d'entrée\" (péchés, héritages ancestraux, objets contaminés) qui ont permis aux blocages de s'installer.\n2.\tL'Autorité du Croyant : Comprenez comment utiliser le nom de Jésus et la puissance du Saint-Esprit comme une \"arme céleste\" pour reprendre le contrôle.\n3.\tLe Nettoyage Complet : Des techniques pour purifier votre cœur et votre environnement physique afin de transformer votre maison en sanctuaire.\n4.\t21 Jours de Prières Ciblées : Un parcours quotidien avec des thèmes précis comme \"Briser les chaînes ancestrales\" ou \"Libérer les écluses des cieux\".\n________________________________________\n🗓️ Votre Parcours de Transformation (21 Jours)\nChaque journée de ce guide est structurée pour une efficacité maximale :\n•\tUn Thème spécifique : Pour attaquer la racine du problème.\n•\tUne Lecture Biblique inspirante : Pour ancrer votre foi dans la Parole.\n•\tUne Prière de Puissance : Des mots précis pour activer votre libération.\n•\tVotre Journal de Victoire : Un espace dédié pour noter vos rêves, vos révélations et les signes de changement dans votre vie.\n________________________________________\n💎 Ce qui rend ce livre unique\nContrairement à d'autres ouvrages, ÉVEIL ASTRAL vous offre des outils interactifs :\n•\tLe Journal de Victoire intégré : Pour suivre l'évolution de votre état intérieur avant et après chaque prière.\n•\tDes Actions Concrètes : Des étapes pratiques pour manifester votre foi dans le monde réel (ex: pardonner, se débarrasser d'objets toxiques).\n•\tUne Préparation Rigoureuse : Avant de commencer les 21 jours, vous bénéficiez de 10 pages de préparation pour vérifier votre \"armure\" spirituelle.\n________________________________________\n🔥 RECLAMEZ VOTRE LIBERTÉ AUJOURD'HUI !\nNe laissez pas une influence invisible dicter votre avenir. Le prix de votre liberté est inestimable, mais l'accès à ce guide est à portée de main.\n« Le Fils de Dieu a paru afin de détruire les œuvres du diable » (1 Jean 3:8). \nReprenez ce qui vous appartient. ",
    "image": "https://image2url.com/r2/default/images/1769896074714-cfca3a69-71c0-4d62-9b59-133265119ddb.png",
    "officialPrice": 10.99,
    "promoPrice": 6.8,
    "chariowLink": "https://spiritux.mychariow.shop/prd_17jtvi",
    "isFeatured": true,
    "isPromo": true,
    "category": "Déblocages spirituels",
    "customFields": [
      {
        "label": "Auteur",
        "value": "Spiritux"
      },
      {
        "label": "Pages",
        "value": ""
      },
      {
        "label": "Format",
        "value": "PDF"
      }
    ]
  },
  {
    "id": "3",
    "title": "L'Art de la Géométrie Sacrée",
    "description": "Les codes secrets de l'univers révélés par les formes parfaites.",
    "summary": "Découvrez comment les structures géométriques régissent la création, de la coquille d'un nautile aux galaxies lointaines. Un manuel pratique pour harmoniser votre environnement et votre esprit par le tracé sacré.",
    "image": "https://images.unsplash.com/photo-1634128221889-82ed6efebfc3?auto=format&fit=crop&q=80&w=600&h=800",
    "officialPrice": 54.99,
    "promoPrice": 34.99,
    "chariowLink": "https://chariow.com/p/geometrie-sacree",
    "isFeatured": true,
    "isPromo": true,
    "category": "Savoir Ancien",
    "customFields": [
      {
        "label": "Format",
        "value": "Livre Illustré"
      },
      {
        "label": "Pages",
        "value": "190"
      }
    ]
  },
  {
    "id": "4",
    "title": "Voyage au Cœur du Chamanisme",
    "description": "Reconnectez-vous aux esprits de la nature et retrouvez votre pouvoir animal.",
    "summary": "Une immersion dans les pratiques ancestrales des peuples premiers. Apprenez à voyager dans le monde d'en bas, à rencontrer vos alliés spirituels et à guérir les blessures de votre lignée.",
    "image": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=600&h=800",
    "officialPrice": 45.99,
    "promoPrice": 27.99,
    "chariowLink": "https://chariow.com/p/chamanisme-pratique",
    "isFeatured": true,
    "isPromo": false,
    "category": "Pratique",
    "customFields": [
      {
        "label": "Tradition",
        "value": "Ancestrale"
      },
      {
        "label": "Pages",
        "value": "230"
      }
    ]
  },
  {
    "id": "5",
    "title": "Astrologie Ésotérique",
    "description": "Lisez votre destin dans le mouvement des astres et l'énergie des constellations.",
    "summary": "Bien plus qu'un horoscope, ce traité explore les liens vibratoires entre les planètes et vos centres énergétiques. Comprenez l'influence cosmique sur votre évolution spirituelle et vos cycles de vie.",
    "image": "https://images.unsplash.com/photo-1532968961962-8a0cb3a2d4f5?auto=format&fit=crop&q=80&w=600&h=800",
    "officialPrice": 42.99,
    "promoPrice": 21.5,
    "chariowLink": "https://chariow.com/p/astrologie-profonde",
    "isFeatured": true,
    "isPromo": true,
    "category": "Cosmologie",
    "customFields": [
      {
        "label": "Niveau",
        "value": "Initié"
      },
      {
        "label": "Pages",
        "value": "310"
      }
    ]
  },
  {
    "id": "6",
    "title": "Le Pouvoir des Cristaux",
    "description": "Maîtrisez les fréquences vibratoires des pierres pour la guérison et la protection.",
    "summary": "Un guide complet sur la lithothérapie ésotérique. Apprenez à purifier, programmer et utiliser les cristaux pour équilibrer vos chakras et créer des boucliers énergétiques puissants.",
    "image": "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&q=80&w=600&h=800",
    "officialPrice": 34.99,
    "promoPrice": 19.99,
    "chariowLink": "https://chariow.com/p/pouvoir-cristaux",
    "isFeatured": true,
    "isPromo": false,
    "category": "Énergétique",
    "customFields": [
      {
        "label": "Type",
        "value": "Guide Pratique"
      },
      {
        "label": "Pages",
        "value": "155"
      }
    ]
  }
];

export const DEFAULT_CONFIG: SiteConfig = {
  "logo": "https://image2url.com/r2/default/images/1769897210973-95599a18-998f-46e7-afe8-7013bfc060be.png",
  "favicon": "https://image2url.com/r2/default/images/1769897210973-95599a18-998f-46e7-afe8-7013bfc060be.png",
  "fbPixelId": "",
  "seoKeywords": [
    "spiritualité",
    "ebooks",
    "bien-être",
    "mystères",
    "méditation",
    "alchimie",
    "éveil spirituel"
  ]
};

export const MOCK_LOCALES: Record<string, LocaleInfo> = {
  'fr-FR': { currency: 'EUR', rate: 1, symbol: '€' },
  'en-US': { currency: 'USD', rate: 1.08, symbol: '$' },
  'en-GB': { currency: 'GBP', rate: 0.85, symbol: '£' },
};

export const TRANSLATIONS: Record<Language, Translations> = {
  "fr": {
    "navHome": "Accueil",
    "navLibrary": "Bibliothèque",
    "navTitle": "Navigation",
    "backToHome": "Retour à l'accueil",
    "backToLibrary": "Retour à la bibliothèque",
    "copyright": "TOUS DROITS RÉSERVÉS \"SPIRITUX\".",
    "loading": "Chargement...",
    "heroSparkle": "Le Sanctuaire du savoir spirituel",
    "heroTitle": "Plongez au Cœur des Sagesses Célestes",
    "heroSubtitle": "Découvrez les secrets de l'univers à travers nos manuscrits sacrés. Un voyage initiatique pour revitaliser votre âme et éclairer votre chemin.",
    "exploreLibrary": "Explorer la Bibliothèque",
    "viewSelection": "Voir la sélection",
    "libraryTitle": "La Bibliothèque Céleste",
    "searchPlaceholder": "Rechercher une sagesse...",
    "filters": "Filtres",
    "noResults": "Aucune sagesse trouvée pour cette recherche.",
    "discover": "Découvrir",
    "getNow": "S'offrir",
    "featuredTitle": "Sanctuaire des Ebooks Vedettes",
    "featuredSubtitle": "Nos manuscrits les plus recherchés",
    "testimonialsTitle": "Paraboles de Sagesse",
    "testimonialsSubtitle": "Enseignements sacrés pour éclairer votre destinée",
    "buyNow": "Acquérir ce savoir millénaire",
    "securePayment": "Paiement sécurisé",
    "instantAccess": "Accès instantané",
    "manuscriptEssence": "L'Essence du Manuscrit",
    "listen": "Écouter",
    "stop": "Arrêter",
    "authenticity": "Authenticité Initiée",
    "authenticityDesc": "Contenu certifié par nos cercles d'études ésotériques.",
    "illumination": "Illumination Directe",
    "illuminationDesc": "L'accès à la connaissance est immédiat et sans délai.",
    "offer": "Offre",
    "sacred": "Sacrée",
    "knowledgeWeapon": "Le savoir est une arme spirituelle",
    "saving": "Économie de",
    "temporalOpportunity": "Opportunité Temporelle",
    "audioError": "Désolé, la lecture audio a échoué. Veuillez réessayer.",
    "shareTitle": "Partager cette sagesse",
    "shareFacebook": "Partager sur Facebook",
    "shareTwitter": "Partager sur X",
    "shareCopy": "Copier le lien",
    "linkCopied": "Lien copié dans le presse-papier !",
    "footerTagline": "Le portail numérique qui vous plonge au cœur des sagesses célestes.",
    "footerContact": "Nous contacter",
    "ebook1Title": "L'Éveil du Troisième Œil",
    "ebook1Desc": "Un guide complet pour explorer vos facultés intuitives et transcender la vision ordinaire.",
    "ebook1Summary": "Ce livre vous enseigne les techniques ancestrales de méditation et de visualisation pour activer la glande pinéale. Apprenez à percevoir les énergies subtiles et à renforcer votre connexion avec l'univers.",
    "ebook2Title": "Les Mystères de l'Alchimie",
    "ebook2Desc": "Transformez le plomb de votre âme en l'or pur de la conscience universelle.",
    "ebook2Summary": "Explorez l'histoire et les pratiques de l'alchimie spirituelle. Un voyage intérieur pour purifier l'esprit et atteindre un état de paix profonde à travers des rituels et des réflexions philosophiques.",
    "ebook3Title": "L'Art de la Géométrie Sacrée",
    "ebook3Desc": "Les codes secrets de l'univers révélés par les formes parfaites.",
    "ebook3Summary": "Découvrez comment les structures géométriques régissent la création, de la coquille d'un nautile aux galaxies lointaines. Un manuel pratique pour harmoniser votre environnement et votre esprit par le tracé sacré.",
    "ebook4Title": "Voyage au Cœur du Chamanisme",
    "ebook4Desc": "Reconnectez-vous aux esprits de la nature et retrouvez votre pouvoir animal.",
    "ebook4Summary": "Une immersion dans les pratiques ancestrales des peuples premiers. Apprenez à voyager dans le monde d'en bas, à rencontrer vos alliés spirituels et à guérir les blessures de votre lignée.",
    "ebook5Title": "Astrologie Ésotérique",
    "ebook5Desc": "Lisez votre destin dans le mouvement des astres et l'énergie des constellations.",
    "ebook5Summary": "Bien plus qu'un horoscope, ce traité explore les liens vibratoires entre les planètes et vos centres énergétiques. Comprenez l'influence cosmique sur votre évolution spirituelle et vos cycles de vie.",
    "ebook6Title": "Le Pouvoir des Cristaux",
    "ebook6Desc": "Maîtrisez les fréquences vibratoires des pierres pour la guérison et la protection.",
    "ebook6Summary": "Un guide complet sur la lithothérapie ésotérique. Apprenez à purifier, programmer et utiliser les cristaux pour équilibrer vos chakras et créer des boucliers énergétiques puissants.",
    "testi1Name": "La Perle de Grand Prix",
    "testi1Text": "Le royaume des cieux est encore semblable à un marchand qui cherche de belles perles. Lorsqu'il en a trouvé une de grand prix, il va vendre tout ce qu'il a, et l'achète. Ne sous-estime jamais la valeur de ton éveil spirituel.",
    "testi1Book": "PARABOLE DU TRÉSOR",
    "testi2Name": "Le Bâtisseur Sage",
    "testi2Text": "Celui qui écoute ces paroles et les met en pratique sera semblable à un homme prudent qui a bâti sa maison sur le roc. La tempête viendra, mais ton esprit demeurera inébranlable car tes fondations sont divines.",
    "testi2Book": "PARABOLE DE LA ROCHE",
    "testi3Name": "Le Grain de Moutarde",
    "testi3Text": "Si vous aviez de la foi comme un grain de sénevé, vous diriez à cette montagne : Transporte-toi d'ici là, et elle se transporterait. Rien ne vous serait impossible si vous croyiez en la puissance qui réside en vous.",
    "testi3Book": "FORCE DE LA FOI",
    "adminPortalTitle": "Portail Mystique",
    "adminPortalSubtitle": "Accès réservé aux Gardiens",
    "adminAccessKey": "Clé d'Accès",
    "adminUnlock": "Déverrouiller",
    "adminDashboardTitle": "Tableau de Bord Spirituel",
    "adminDashboardSubtitle": "Gérez vos énergies numériques.",
    "adminSaveSuccess": "Changements sauvegardés !",
    "adminDeleteConfirmTitle": "Action Irréversible",
    "adminDeleteConfirmText": "Voulez-vous vraiment bannir cet ouvrage ?",
    "adminCancel": "Annuler",
    "adminDelete": "Supprimer"
  },
  "en": {
    "navHome": "Home",
    "navLibrary": "Library",
    "navTitle": "Navigation",
    "backToHome": "Back to Home",
    "backToLibrary": "Back to Library",
    "copyright": "ALL RIGHTS RESERVED \"SPIRITUX\".",
    "loading": "Loading...",
    "heroSparkle": "The Sanctuary of Spiritual Knowledge",
    "heroTitle": "Dive into the Heart of Celestial Wisdom",
    "heroSubtitle": "Discover the secrets of the universe through our sacred manuscripts. An initiatory journey to revitalize your soul and enlighten your path.",
    "exploreLibrary": "Explore Library",
    "viewSelection": "View Selection",
    "libraryTitle": "The Celestial Library",
    "searchPlaceholder": "Search for wisdom...",
    "filters": "Filters",
    "noResults": "No wisdom found for this search.",
    "discover": "Discover",
    "getNow": "Get Now",
    "featuredTitle": "Featured Ebooks Sanctuary",
    "featuredSubtitle": "Our most sought-after manuscripts",
    "testimonialsTitle": "Parables of Wisdom",
    "testimonialsSubtitle": "Sacred teachings to enlighten your destiny",
    "buyNow": "Acquire this ancient knowledge",
    "securePayment": "Secure Payment",
    "instantAccess": "Instant Access",
    "manuscriptEssence": "The Essence of the Manuscript",
    "listen": "Listen",
    "stop": "Stop",
    "authenticity": "Initiated Authenticity",
    "authenticityDesc": "Content certified by our esoteric study circles.",
    "illumination": "Direct Illumination",
    "illuminationDesc": "Access to knowledge is immediate and without delay.",
    "offer": "Special",
    "sacred": "Offer",
    "knowledgeWeapon": "Knowledge is a spiritual weapon",
    "saving": "Save",
    "temporalOpportunity": "Temporal Opportunity",
    "audioError": "Sorry, audio playback failed. Please try again.",
    "shareTitle": "Share this wisdom",
    "shareFacebook": "Share on Facebook",
    "shareTwitter": "Share on X",
    "shareCopy": "Copy link",
    "linkCopied": "Link copied to clipboard!",
    "footerTagline": "The digital portal that plunges you into the heart of celestial wisdom.",
    "footerContact": "Contact Us",
    "ebook1Title": "Awakening the Third Eye",
    "ebook1Desc": "A complete guide to exploring your intuitive faculties and transcending ordinary vision.",
    "ebook1Summary": "This book teaches you ancient meditation and visualization techniques to activate the pineal gland. Learn to perceive subtle energies and strengthen your connection with the universe.",
    "ebook2Title": "The Mysteries of Alchemy",
    "ebook2Desc": "Transform the lead of your soul into the pure gold of universal consciousness.",
    "ebook2Summary": "Explore the history and practices of spiritual alchemy. An inner journey to purify the spirit and achieve a state of deep peace through rituals and philosophical reflections.",
    "ebook3Title": "The Art of Sacred Geometry",
    "ebook3Desc": "The secret codes of the universe revealed through perfect forms.",
    "ebook3Summary": "Discover how geometric structures govern creation, from a nautilus shell to distant galaxies. A practical manual to harmonize your environment and mind through sacred drawing.",
    "ebook4Title": "Journey to the Heart of Shamanism",
    "ebook4Desc": "Reconnect with nature spirits and find your animal power.",
    "ebook4Summary": "An immersion into the ancestral practices of indigenous peoples. Learn to travel into the lower world, meet your spiritual allies, and heal the wounds of your lineage.",
    "ebook5Title": "Esoteric Astrology",
    "ebook5Desc": "Read your destiny in the movement of stars and the energy of constellations.",
    "ebook5Summary": "More than just a horoscope, this treatise explores the vibratory links between planets and your energy centers. Understand the cosmic influence on your spiritual evolution and life cycles.",
    "ebook6Title": "The Power of Crystals",
    "ebook6Desc": "Master the vibratory frequencies of stones for healing and protection.",
    "ebook6Summary": "A complete guide to esoteric lithotherapy. Learn to purify, program, and use crystals to balance your chakras and create powerful energy shields.",
    "testi1Name": "The Pearl of Great Price",
    "testi1Text": "The kingdom of heaven is like a merchant looking for fine pearls. When he found one of great value, he went away and sold everything he had and bought it. Never underestimate the value of your spiritual awakening.",
    "testi1Book": "PARABLE OF THE TREASURE",
    "testi2Name": "The Wise Builder",
    "testi2Text": "Everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock. The storm will come, but your spirit will remain unshakable for your foundations are divine.",
    "testi2Book": "PARABLE OF THE ROCK",
    "testi3Name": "The Mustard Seed",
    "testi3Text": "If you have faith as small as a mustard seed, you can say to this mountain, \"Move from here to there,\" and it will move. Nothing will be impossible for you if you believe in the power that resides within you.",
    "testi3Book": "STRENGTH OF FAITH",
    "adminPortalTitle": "Mystic Portal",
    "adminPortalSubtitle": "Access reserved for Guardians",
    "adminAccessKey": "Access Key",
    "adminUnlock": "Unlock",
    "adminDashboardTitle": "Spiritual Dashboard",
    "adminDashboardSubtitle": "Manage your digital energies.",
    "adminSaveSuccess": "Changes saved!",
    "adminDeleteConfirmTitle": "Irreversible Action",
    "adminDeleteConfirmText": "Do you really want to banish this work?",
    "adminCancel": "Cancel",
    "adminDelete": "Delete"
  },
  "es": {
    "navHome": "Inicio",
    "navLibrary": "Biblioteca",
    "navTitle": "Navegación",
    "backToHome": "Volver al inicio",
    "backToLibrary": "Volver a la biblioteca",
    "copyright": "TODOS LOS DERECHOS RESERVADOS \"SPIRITUX\".",
    "loading": "Cargando...",
    "heroSparkle": "El Santuario del conocimiento espiritual",
    "heroTitle": "Sumérgete en el Corazón de la Sabiduría Celestial",
    "heroSubtitle": "Descubre los secretos del universe a través de nuestros manuscritos sagrados. Un viaje iniciático para revitalizar tu alma e iluminar tu camino.",
    "exploreLibrary": "Explorar Biblioteca",
    "viewSelection": "Ver selección",
    "libraryTitle": "La Biblioteca Celestial",
    "searchPlaceholder": "Buscar una sabiduría...",
    "filters": "Filtros",
    "noResults": "No se encontró sabiduría para esta búsqueda.",
    "discover": "Découvrir",
    "getNow": "Obtener",
    "featuredTitle": "Santuario de Ebooks Destacados",
    "featuredSubtitle": "Nuestros manuscritos más buscados",
    "testimonialsTitle": "Parábolas de Sabiduría",
    "testimonialsSubtitle": "Enseñanzas sagradas para iluminar tu destino",
    "buyNow": "Adquirir este saber milenario",
    "securePayment": "Pago seguro",
    "instantAccess": "Acceso instantáneo",
    "manuscriptEssence": "La Esencia del Manuscrito",
    "listen": "Escuchar",
    "stop": "Detener",
    "authenticity": "Autenticidad Iniciada",
    "authenticityDesc": "Contenido certificado par nuestros círculos de estudio esotérico.",
    "illumination": "Iluminación Directa",
    "illuminationDesc": "El acceso al conocimiento es inmediato y sin demora.",
    "offer": "Oferta",
    "sacred": "Sagrada",
    "knowledgeWeapon": "El conocimiento est un arma espiritual",
    "saving": "Ahorro de",
    "temporalOpportunity": "Oportunidad Temporal",
    "audioError": "Lo sentimos, la reproducción de audio falló. Inténtalo de nuevo.",
    "shareTitle": "Compartir esta sabiduría",
    "shareFacebook": "Compartir en Facebook",
    "shareTwitter": "Compartir en X",
    "shareCopy": "Copiar enlace",
    "linkCopied": "¡Enlace copiado al portapapeles!",
    "footerTagline": "El portal digital que te sumerge en el corazón de la sabiduría celestial.",
    "footerContact": "Contáctenos",
    "ebook1Title": "El Despertar del Tercer Ojo",
    "ebook1Desc": "Una guía completa para explorar sus facultades intuitivas et trascender la visión ordinaria.",
    "ebook1Summary": "Este libro le enseña técnicas ancestrales de meditación et visualización para activar la glándula pineal. Aprenda a percibir energías sutiles y fortalezca su conexión con el universo.",
    "ebook2Title": "Los Misterios de la Alquimia",
    "ebook2Desc": "Transforma el plomo de tu alma en el oro puro de la conciencia universal.",
    "ebook2Summary": "Explore la historia y las prácticas de la alquimia espiritual. Un viaje interior para purificar el espíritu y lograr un estado de paz profunda a través de rituales y reflexiones filosóficas.",
    "ebook3Title": "El Arte de la Geometría Sacrée",
    "ebook3Desc": "Los códigos secretos del universo revelados a través de formas perfectas.",
    "ebook3Summary": "Descubra cómo las estructuras geométricas rigen la creación. Un manual práctico para armonizar su entorno y su mente a través del trazado sagrado.",
    "ebook4Title": "Viaje al Corazón del Chamanismo",
    "ebook4Desc": "Reconéctate con los espíritus de la naturaleza y encuentra tu poder animal.",
    "ebook4Summary": "Una inmersión en las prácticas ancestrales. Aprenda a viajar al mundo de abajo, a conocer a sus aliados espirituales y a sanar las heridas de su linaje.",
    "ebook5Title": "Astrología Esotérica",
    "ebook5Desc": "Lea su destino en el movimiento de los astros y la energía de las constelaciones.",
    "ebook5Summary": "Mucho más que un horóscopo, este tratado explora los vínculos vibratorios entre los planetas y sus centros energéticos. Comprenda la influencia cósmica en su evolución espiritual.",
    "ebook6Title": "El Poder de los Cristaux",
    "ebook6Desc": "Domina las frecuencias vibratorias de las piedras para la curación y la protección.",
    "ebook6Summary": "Una guía completa sobre litoterapia esotérica. Aprenda a purificar, programar y utilizar cristales para equilibrar sus chakras y crear poderosos escudos energéticos.",
    "testi1Name": "La Perle de Grand Valor",
    "testi1Text": "El reino de los cielos es semejante a un mercader que busca buenas perlas, que habiendo hallado una perla preciosa, fue y vendió todo lo que tenía, y la compró. Nunca subestimes el valor de tu despertar espiritual.",
    "testi1Book": "PARÁBOLA DEL TESORO",
    "testi2Name": "El Edificador Sabio",
    "testi2Text": "Cualquiera, pues, que me oye estas palabras, y las hace, le compararé a un hombre prudente, que edificó su casa sobre la roca. Vendrá la tempestad, pero tu espíritu permanecerá inquebrantable.",
    "testi2Book": "PARÁBOLA DE LA ROCA",
    "testi3Name": "El Grano de Mostaza",
    "testi3Text": "Si tuviereis fe como un grano de mostaza, diréis a este monte: Pásate de aquí allá, y se pasará; y nada os será imposible si creéis en el poder que reside en vuestro interior.",
    "testi3Book": "FUERZA DE LA FE",
    "adminPortalTitle": "Portal Místico",
    "adminPortalSubtitle": "Acceso reservado a los Guardianes",
    "adminAccessKey": "Clave de Acceso",
    "adminUnlock": "Desbloquear",
    "adminDashboardTitle": "Panel Espiritual",
    "adminDashboardSubtitle": "Gestiona tus energías digitales.",
    "adminSaveSuccess": "¡Cambios guardados!",
    "adminDeleteConfirmTitle": "Acción Irreversible",
    "adminDeleteConfirmText": "¿De verdad quieres desterrar esta obra?",
    "adminCancel": "Cancelar",
    "adminDelete": "Eliminar"
  },
  "de": {
    "navHome": "Startseite",
    "navLibrary": "Bibliothek",
    "navTitle": "Navigation",
    "backToHome": "Zurück zur Startseite",
    "backToLibrary": "Zurück zur Bibliothek",
    "copyright": "ALLE RECHTE VORBEHALTEN \"SPIRITUX\".",
    "loading": "Laden...",
    "heroSparkle": "Das Heiligtum des spirituellen Wissens",
    "heroTitle": "Tauchen Sie ein in das Herz der himmlischen Weisheit",
    "heroSubtitle": "Entdecken Sie die Geheimnisse des Universums durch unsere heiligen Manuskripte. Eine Initiationsreise, um Ihre Seele zu revitalisieren und Ihren Weg zu erleuchten.",
    "exploreLibrary": "Bibliothek erkunden",
    "viewSelection": "Auswahl ansehen",
    "libraryTitle": "Die himmlische Bibliothek",
    "searchPlaceholder": "Suche nach Weisheit...",
    "filters": "Filter",
    "noResults": "Keine Weisheit für diese Suche gefunden.",
    "discover": "Entdecken",
    "getNow": "Holen",
    "featuredTitle": "Heiligtum der vorgestellten Ebooks",
    "featuredSubtitle": "Unsere begehrtesten Manuskripte",
    "testimonialsTitle": "Gleichnisse der Weisheit",
    "testimonialsSubtitle": "Heilige Lehren zur Erleuchtung Ihres Schicksals",
    "buyNow": "Dieses jahrtausendealte Wissen erwerben",
    "securePayment": "Sichere Zahlung",
    "instantAccess": "Sofortiger Zugriff",
    "manuscriptEssence": "Die Essenz des Manuskripts",
    "listen": "Anhören",
    "stop": "Stopp",
    "authenticity": "Initiierte Authentizität",
    "authenticityDesc": "Inhalt zertifiziert durch unsere esoterischen Studienkreise.",
    "illumination": "Direkte Erleuchtung",
    "illuminationDesc": "Der Zugang zu Wissen erfolgt sofort und ohne Verzögerung.",
    "offer": "Angebot",
    "sacred": "Heiliges",
    "knowledgeWeapon": "Wissen ist eine spirituelle Waffe",
    "saving": "Ersparnis",
    "temporalOpportunity": "Temporale Gelegenheit",
    "audioError": "Leider ist die Audiowiedergabe fehlgeschlagen. Bitte versuchen Sie es erneut.",
    "shareTitle": "Teilen Sie diese Weisheit",
    "shareFacebook": "Auf Facebook teilen",
    "shareTwitter": "Auf X teilen",
    "shareCopy": "Link kopieren",
    "linkCopied": "Link in die Zwischenablage kopiert!",
    "footerTagline": "Das digitale Portal, das Sie in das Herz der himmlischen Weisheit eintauchen lässt.",
    "footerContact": "Kontaktieren Sie uns",
    "ebook1Title": "Das Erwachen des Dritten Auges",
    "ebook1Desc": "Ein umfassender Leitfaden zur Erforschung Ihrer intuitiven Fähigkeiten und zur Überwindung der gewöhnlichen Sichtweise.",
    "ebook1Summary": "Dieses Buch lehrt Sie uralte Meditations- und Visualisierungstechniken zur Aktivierung der Zirbeldrüse. Lernen Sie, subtile Energien wahrzunehmen und Ihre Verbindung zum Universum zu stärken.",
    "ebook2Title": "Die Geheimnisse der Alchemie",
    "ebook2Desc": "Verwandeln Sie das Blei Ihrer Seele in das reine Gold des universellen Bewusstseins.",
    "ebook2Summary": "Erforschen Sie die Geschichte und Praktiken der spirituellen Alchemie. Eine innere Reise zur Reinigung des Geistes und zur Erlangung eines Zustands tiefen Friedens durch Rituale und philosophische Überlegungen.",
    "ebook3Title": "Die Kunst der Heiligen Geometrie",
    "ebook3Desc": "Die geheimen Codes des Universums, offenbart durch perfekte Formen.",
    "ebook3Summary": "Entdecken Sie, wie geometrische Strukturen die Schöpfung regieren. Ein praktisches Handbuch, um Ihre Umgebung und Ihren Geist durch heiliges Zeichnen zu harmonisieren.",
    "ebook4Title": "Reise zum Herzen des Schamanismus",
    "ebook4Desc": "Verbinden Sie sich wieder mit den Naturgeistern und finden Sie Ihre tierische Kraft.",
    "ebook4Summary": "Ein Eintauchen in die uralten Praktiken der indigenen Völker. Lernen Sie, in die Unterwelt zu reisen, Ihre spirituellen Verbündeten zu treffen und die Wunden Ihrer Ahnenlinie zu heilen.",
    "ebook5Title": "Esoterische Astrologie",
    "ebook5Desc": "Lesen Sie Ihr Schicksal in der Bewegung der Sterne und der Energie der Sternbilder.",
    "ebook5Summary": "Weit mehr als ein Horoskop erforscht diese Abhandlung die Schwingungsverbindungen zwischen den Planeten und Ihren Energiezentren. Verstehen Sie den kosmischen Einfluss auf Ihre spirituelle Entwicklung.",
    "ebook6Title": "Die Kraft der Kristalle",
    "ebook6Desc": "Meistern Sie die Schwingungsfrequenzen der Steine zur Heilung und zum Schutz.",
    "ebook6Summary": "Ein umfassender Leitfaden zur esoterischen Lithotherapy. Lernen Sie, Kristalle zu reinigen, zu programmieren und zu verwenden, um Ihre Chakren auszugleichen und kraftvolle Energieschilde zu schaffen.",
    "testi1Name": "Die Kostbare Perle",
    "testi1Text": "Das Himmelreich ist gleich einem Kaufmann, der gute Perlen suchte. Und da er eine kostbare Perle fand, ging er hin und verkaufte alles, was er hatte, und kaufte sie. Unterschätze niemals den Wert deines Erwachens.",
    "testi1Book": "GLEICHNIS VOM SCHATZ",
    "testi2Name": "Der Kluge Baumeister",
    "testi2Text": "Wer diese meine Rede hört und tut sie, der gleicht einem klugen Mann, der sein Haus auf Fels baute. Der Sturm wird kommen, aber dein Geist wird unerschütterlich bleiben, denn dein Fundament ist göttlich.",
    "testi2Book": "GLEICHNIS VOM FELS",
    "testi3Name": "Das Senfkorn",
    "testi3Text": "Wenn ihr Glauben habt wie un ein Senfkorn, so mögt ihr sagen zu diesem Berge: Hebe dich von hinnen dorthin! so wird er sich heben; und euch wird nichts unmöglich sein, wenn ihr an die Kraft in euch glaubt.",
    "testi3Book": "KRAFT DES GLAUBENS",
    "adminPortalTitle": "Mystisches Portal",
    "adminPortalSubtitle": "Zugang den Wächtern vorbehalten",
    "adminAccessKey": "Zugangsschlüssel",
    "adminUnlock": "Freischalten",
    "adminDashboardTitle": "Spirituelles Dashboard",
    "adminDashboardSubtitle": "Verwalten Sie Ihre digitalen Energien.",
    "adminSaveSuccess": "Änderungen gespeichert!",
    "adminDeleteConfirmTitle": "Unumkehrbare Aktion",
    "adminDeleteConfirmText": "Möchten Sie dieses Werk wirklich verbannen?",
    "adminCancel": "Abbrechen",
    "adminDelete": "Löschen"
  },
  "it": {
    "navHome": "Home",
    "navLibrary": "Biblioteca",
    "navTitle": "Navigazione",
    "backToHome": "Torna alla Home",
    "backToLibrary": "Torna alla Biblioteca",
    "copyright": "TUTTI I DIRITTI RISERVATI \"SPIRITUX\".",
    "loading": "Caricamento...",
    "heroSparkle": "Il Santuario della Conoscenza Spirituale",
    "heroTitle": "Immergiti nel Cuore delle Saggezze Celesti",
    "heroSubtitle": "Scopri i segreti dell'universo attraverso i nostri manoscritti sacri. Un viaggio iniziatico per rivitalizzare la tua anima e illuminare il tuo cammino.",
    "exploreLibrary": "Esplora la Biblioteca",
    "viewSelection": "Vedi selezione",
    "libraryTitle": "La Biblioteca Celeste",
    "searchPlaceholder": "Cerca una saggezza...",
    "filters": "Filtri",
    "noResults": "Nessuna saggezza trovata per questa ricerca.",
    "discover": "Scopri",
    "getNow": "Acquista",
    "featuredTitle": "Santuario degli Ebook in Primo Piano",
    "featuredSubtitle": "I nostri manoscritti più ricercati",
    "testimonialsTitle": "Parabole di Saggezza",
    "testimonialsSubtitle": "Insegnamenti sacri per illuminare il tuo destino",
    "buyNow": "Acquista questo sapere millenario",
    "securePayment": "Pagamento sicuro",
    "instantAccess": "Accesso istantaneo",
    "manuscriptEssence": "L'Essenza del Manoscritto",
    "listen": "Ascolta",
    "stop": "Ferma",
    "authenticity": "Autenticità Iniziata",
    "authenticityDesc": "Contenuto certificato dai nostri circoli di studi esoterici.",
    "illumination": "Illuminazione Diretta",
    "illuminationDesc": "L'accesso alla conoscenza è immediato e senza ritardi.",
    "offer": "Offerta",
    "sacred": "Sacra",
    "knowledgeWeapon": "La conoscenza è un'arma spirituale",
    "saving": "Risparmio di",
    "temporalOpportunity": "Opportunità Temporale",
    "audioError": "Spiacenti, la riproduzione audio è fallita. Riprova.",
    "shareTitle": "Condividi questa saggezza",
    "shareFacebook": "Condividi su Facebook",
    "shareTwitter": "Condividi su X",
    "shareCopy": "Copia link",
    "linkCopied": "Link copiato negli appunti!",
    "footerTagline": "Il portale digitale che ti immerge nel cuore delle saggezze celesti.",
    "footerContact": "Contattaci",
    "ebook1Title": "L'Risveglio del Terzo Occhio",
    "ebook1Desc": "Una guida completa per esplorare le tue facoltà intuitive e trascendere la visione ordinaria.",
    "ebook1Summary": "Questo libro ti insegna le antiche tecniche di meditazione e visualizzazione per attivare la ghiandola pineale. Impara a percepire le energie sottili e a rafforzare la tua connessione con l'universo.",
    "ebook2Title": "I Misteri dell'Alchimia",
    "ebook2Desc": "Trasforma il piombo della tua anima nell'oro puro della coscienza universale.",
    "ebook2Summary": "Esplora la storia e le pratiche dell'alchimia spirituale. Un viaggio interiore per purificare lo spirito e raggiungere uno stato di pace profonda attraverso rituali e riflessioni filosofiche.",
    "ebook3Title": "L'Arte della Geometria Sacra",
    "ebook3Desc": "I codici segreti dell'universo rivelati attraverso forme perfette.",
    "ebook3Summary": "Scopri come le strutture geometriche governano la creazione. Un manuale pratico per armonizzare il tuo ambiente e la tua mente attraverso il disegno sacro.",
    "ebook4Title": "Viaggio nel Cuore dello Sciamanesimo",
    "ebook4Desc": "Riconnettiti con gli spiriti della natura e ritrova il tuo potere animale.",
    "ebook4Summary": "Un'immersione nelle pratiche ancestrali dei popoli indigeni. Impara a viaggiare nel mondo di sotto, incontrare i tuoi alleati spirituali e guarire le ferite del tuo lignaggio.",
    "ebook5Title": "Astrologia Esoterica",
    "ebook5Desc": "Leggi il tuo destino nel movimento degli astri e nell'energia delle costellazioni.",
    "ebook5Summary": "Molto più di un semplice oroscopo, questo trattato esplora i legami vibratori tra i pianeti e i tuoi centri energetici. Comprendi l'influenza cosmica sulla tua evoluzione spirituale.",
    "ebook6Title": "Il Potere dei Cristalli",
    "ebook6Desc": "Padroneggia le frequenze vibratorie delle pietre per la guarigione e la protezione.",
    "ebook6Summary": "Una guida completa alla litoterapia esoterica. Impara a purificare, programmare e utilizzare i cristalli per equilibrare i tuoi chakra e creare potenti scudi energetici.",
    "testi1Name": "La Perla di Gran Prezzo",
    "testi1Text": "Il regno dei cieli è simile a un mercante che va in cerca di belle perle; trovata una perla di grande valore, va, vende tutti i suoi averi e la compra. Non sottovalutare mai il valore del tuo risveglio spirituale.",
    "testi1Book": "PARABOLA DEL TESORO",
    "testi2Name": "Il Costruttore Saggio",
    "testi2Text": "Chiunque ascolta queste mie parole e le mette in pratica, sarà simile a un uomo saggio, che ha costruito la sua casa sulla roccia. Verrà la tempesta, ma il tuo spirito rimarrà incrollabile.",
    "testi2Book": "PARABOLA DELLA ROCCIA",
    "testi3Name": "Il Granello di Senape",
    "testi3Text": "Se aveste fede quanto un granello di senape, potrete dire a questo monte: \"Passa da qui a là\", ed esso vi passerà; e nulla vi sarà impossibile se credete nel potere che risiede in voi.",
    "testi3Book": "FORZA DELLA FEDE",
    "adminPortalTitle": "Portale Mistico",
    "adminPortalSubtitle": "Accesso riservato ai Guardiani",
    "adminAccessKey": "Chiave di Accesso",
    "adminUnlock": "Sblocca",
    "adminDashboardTitle": "Pannello Spirituale",
    "adminDashboardSubtitle": "Gestisci le tue energie digitali.",
    "adminSaveSuccess": "Cambiamenti salvati!",
    "adminDeleteConfirmTitle": "Azione Irreversibile",
    "adminDeleteConfirmText": "Vuoi davvero bandire quest'opera?",
    "adminCancel": "Annulla",
    "adminDelete": "Elimina"
  }
};
